### ISSUE TITLE
Plugin stopped working...

### ISSUE THREAD

**Issue by marko-lazovic** [tomimaen/zilla-likes#3]
Hi, 

I got ZillaLikes plugin with the WP theme I bought for my website. Everyting worked fine until the latest WP version (5.7.1 at the moment) when the plugin stopped working. I have errors in the console, seems to be some jQuery error, but I don't know how to fix it. I'm sending the screenshot so you can see the errors in the console.  Can you please help with this?

![ZillaLikes error](https://user-images.githubusercontent.com/57508017/117503220-f1a92180-af80-11eb-8258-0e0835e126e0.png)

**Comment by tomimaen** [comment]
Hi,

It seems that you have an older version of the ZillaLikes plugin active, which still uses the deprecated `$().live` function. The deprecation issue is caused by the update of jQuery version in WordPress 5.6.

Try downloading this plugin from [here](https://github.com/tomimaen/zilla-likes/archive/refs/heads/master.zip) and replace the old plugin in your site with this one.

**Comment by marko-lazovic** [comment]
Hi,

Thank you very much! I'll let you know if everything works when I replace older version with the one you provided here.

Just one more question before I do it - replacing old plugin with this new version won't affect the existing number of likes on the site, right?

**Comment by marko-lazovic** [comment]
Hi,

Thank you very much for all the help! I've updated the plugin, everything works fine now and all the old likes are still there.

And also a big thank you for your work and keeping this plugin alive, since it's not officially supported by the original developer anymore. 

Cheers!
